### ISSUE TITLE
AWSConfig should be AWS.Config

### ISSUE THREAD

**Issue by exoego** [exoego/aws-sdk-scalajs-facade#131]
Currently, AWSConfig is just Scala.js-defined js.Object.
It should be https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html ?

**Comment by unarist** [comment]
Note that service constructors (e.g. [`new AWS.DynamoDB()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property)) doesn't expects an [`AWS.Config`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html) instance.

Passing new `AWS.Config` instance to the constructor overrides global settings in `AWS.config`.

**Comment by exoego** [comment]
OK, so current implementation is safer.
