### ISSUE TITLE
AWS.config.credentials can be null

### ISSUE THREAD

**Issue by unarist** [exoego/aws-sdk-scalajs-facade#132]
`AWS.config.credentials` is typed as `js.UndefOr[AWSCredentials]` in this facade, but actually it can be `null`. I saw `null` value in this property when I run without `.aws/credentials` file.

c.f. https://github.com/aws/aws-sdk-js/blob/212e2e38da1a77ad9dba9f7c764a1414e54c5046/lib/config.d.ts#L184-L187

**Comment by exoego** [comment]
Try `AWS.config.credentials.contains(null)` to detect it is null.
This repository do not use `T | Null` for typing nullable values, since reference types are nullable by default in Scala 2.x.
