### ISSUE TITLE
Add SNS FIFO support

### ISSUE THREAD

**Issue by yurizhuravel** [exoego/aws-sdk-scalajs-facade#287]
Hi, and first of all thanks for all the good work - I find the library very useful for writing lambdas in Scala for AWS.

Amazon has recently [introduced FIFO SNS topics](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-sns-introduces-fifo-topics-with-strict-ordering-and-deduplication-of-messages/), which look like a very useful thing - do you have plans to add support for them in the near future? Looks like [Publish](https://github.com/exoego/aws-sdk-scalajs-facade/blob/master/services/sns/src/main/scala/facade/amazonaws/services/SNS.scala#L984) doesn't currently cater for things like `MessageGroupId` or `MessageDeducplicationId`, which are needed to use the new SNS FIFO functionality.

Thanks in advance!

**Comment by yurizhuravel** [comment]
I have modified this bit for use in my local codebase - could drop a pull request for consideration if you don't mind. Haven't got the permissions though

**Comment by exoego** [comment]
I will update the base aws-sdk to latest and publish in a couple of days.

**Comment by exoego** [comment]
> Looks like [Publish](https://github.com/exoego/aws-sdk-scalajs-facade/blob/master/services/sns/src/main/scala/facade/amazonaws/services/SNS.scala#L984) doesn't currently cater for things like `MessageGroupId` or `MessageDeducplicationId`, which are needed to use the new SNS FIFO functionality.

Added in PR #295 https://github.com/exoego/aws-sdk-scalajs-facade/pull/295/files#diff-2281ed8a389688abbac3878353e29e23447bf32662a7edff3c2c738b753aca03R990-R991

**Comment by exoego** [comment]
I think the latest release v0.32.0-v2.798.0 supports SNS FIFO.
It would be helpful if you find issue on the version.
