### ISSUE TITLE
Missing CognitoIdentityCredentials

### ISSUE THREAD

**Issue by cornerman** [exoego/aws-sdk-scalajs-facade#345]
Just realized that there is no facade for `CognitoIdentityCredentials` (see https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html).

I understand that these facades are at least partially generated, so I was just wondering, what we could do to integrate it.

**Comment by exoego** [comment]
Thanks for a report.
It seems that everything in `lib/credentials` has no facade at all.
I will consider to add facade manually at first.

**Comment by exoego** [comment]
FYI: `CognitoIdentityCredentials` and rest of `Credentials` implementions are published in `aws-sdk-scalajs-facade-credentials`
https://github.com/exoego/aws-sdk-scalajs-facade/releases/tag/v0.33.0-v2.892.0
