### ISSUE TITLE
Wrong Type for apigatewaymanagementapi.Data

### ISSUE THREAD

**Issue by cornerman** [exoego/aws-sdk-scalajs-facade#440]
We have a type alias for the Data that we can send in the apigatewaymangementapi: https://github.com/exoego/aws-sdk-scalajs-facade/blob/0b2865fc058733e1695dc348cdb22a50aba302c1/aws-sdk-v2/services/apigatewaymanagementapi/src/main/scala/facade/amazonaws/services/ApiGatewayManagementApi.scala#L11

But actually, it does not support `js.Array[Byte]`. When I send a `js.Array[Byte]`, I get the exception:
```
Expected params.Data to be a string, Buffer, Stream, Blob, or typed array object
```

**Comment by exoego** [comment]
Thanks, I will check.

It is `BlobType` in aws sdk definition, and I might be wrong to convert them into corresponding JS types
