### ISSUE TITLE
Relase for scala 3

### ISSUE THREAD

**Issue by cornerman** [exoego/aws-sdk-scalajs-facade#468]
I could not find a release for scala-3. I can see that the projects cross-builds to it though. Would you mind making one with the current master? If there are blockers left, I can try to help.

**Comment by exoego** [comment]
Sorry, I have no bandwidth to maintain this repo.

Please consider [ScalablyTyped](https://scalablytyped.org/docs/readme.html) instead 🙇
I believe it supports aws-sdk-js-v3 too.
