### ISSUE TITLE
Support aws-sdk-js-v3

### ISSUE THREAD

**Issue by exoego** [exoego/aws-sdk-scalajs-facade#50]
https://github.com/aws/aws-sdk-js-v3

Ref. #49

**Comment by oyvindberg** [comment]
In case it's useful to you I added the libraries i found to my build now, see https://github.com/oyvindberg/ScalablyTyped/commit/ddd52276a2d631d709bfa6aa43597b8af7b78515

**Comment by exoego** [comment]
aws-sdk-js-v3 is finally out.
https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.0.0
